(deftheme luke
  "Created 2025-11-27.")

(custom-theme-set-faces
 'luke
 '(default ((t (:underline nil :overline nil :extend nil :strike-through nil :box nil :inverse-video nil :foreground "#dde0f8" :background "#2f343f" :stipple nil :inherit nil))))
 '(cursor ((t (:background "#e08ca0"))))
 '(escape-glyph ((t (:foreground "#e8add2"))))
 '(homoglyph ((t (:foreground "#e8add2"))))
 '(minibuffer-prompt ((t (:foreground "#c4abfe" :inherit (bold)))))
 '(highlight ((t (:background "#573f5d"))))
 '(region ((t (:extend t :foreground "#c4abfe" :background "#424381"))))
 '(shadow ((t (:foreground "#aea7c3"))))
 '(secondary-selection ((t (:extend t :foreground "#aea7c3" :background "#3c3e55"))))
 '(trailing-whitespace ((((class color) (background light)) (:background "red1")) (((class color) (background dark)) (:background "red1")) (t (:inverse-video t))))
 '(font-lock-bracket-face ((t (:foreground "#dde0f8"))))
 '(font-lock-builtin-face ((t (:foreground "#aea7c3" :inherit (bold-italic)))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#e8add2" :inherit (italic)))))
 '(font-lock-comment-face ((t (:foreground "#e8add2" :inherit (italic)))))
 '(font-lock-constant-face ((t (:foreground "#dde0f8"))))
 '(font-lock-delimiter-face ((t (:foreground "#dde0f8"))))
 '(font-lock-doc-face ((t (:foreground "#aea7c3" :inherit (italic)))))
 '(font-lock-doc-markup-face ((t (:foreground "#aea7c3" :inherit (italic)))))
 '(font-lock-escape-face ((t (:inherit (font-lock-regexp-grouping-backslash)))))
 '(font-lock-function-call-face ((t (:foreground "#c4abfe"))))
 '(font-lock-function-name-face ((t (:foreground "#c4abfe"))))
 '(font-lock-keyword-face ((t (:foreground "#c4abfe" :inherit (bold)))))
 '(font-lock-negation-char-face ((t (:foreground "#dde0f8"))))
 '(font-lock-number-face ((t (:foreground "#dde0f8"))))
 '(font-lock-misc-punctuation-face ((t (:foreground "#dde0f8"))))
 '(font-lock-operator-face ((t (:foreground "#c4abfe" :inherit (bold)))))
 '(font-lock-preprocessor-face ((t (:foreground "#aea7c3" :inherit (bold-italic)))))
 '(font-lock-property-name-face ((t (:inherit (font-lock-variable-name-face)))))
 '(font-lock-property-use-face ((t (:inherit (font-lock-property-name-face)))))
 '(font-lock-punctuation-face ((t (:foreground "#dde0f8"))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#c4abfe" :inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#c4abfe" :inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#aea7c3"))))
 '(font-lock-type-face ((t (:foreground "#aea7c3" :inherit (bold-italic)))))
 '(font-lock-variable-name-face ((t (:inherit (italic)))))
 '(font-lock-variable-use-face ((t (:inherit (italic)))))
 '(font-lock-warning-face ((t (:foreground "#c0b080" :inherit (bold)))))
 '(button ((t (:foreground "#e8add2" :inherit (underline)))))
 '(link ((t (:foreground "#e8add2" :inherit (underline)))))
 '(link-visited ((t (:foreground "#e8add2" :inherit (underline)))))
 '(fringe ((t (:foreground "#e8add2" :background "#2f343f"))))
 '(header-line ((t (:foreground "#aea7c3" :background "#3c3e55"))))
 '(tooltip ((t (:foreground "#e8add2" :background "#573f5d"))))
 '(mode-line ((t (:box (:line-width (1 . 1) :color "#757a90" :style nil) :foreground "#c4abfe" :background "#424381"))))
 '(mode-line-buffer-id ((t (:foreground "#c4abfe" :inherit (bold)))))
 '(mode-line-emphasis ((t (:foreground "#c4abfe" :inherit (bold)))))
 '(mode-line-highlight ((t (:background "#573f5d"))))
 '(mode-line-inactive ((t (:box (:line-width (1 . 1) :color "#757a90" :style nil) :foreground "#aea7c3" :background "#3c3e55"))))
 '(isearch ((t (:foreground "#dde0f8" :background "#424381"))))
 '(isearch-fail ((t (:inherit (underline bold)))))
 '(lazy-highlight ((t (:foreground "#aea7c3" :inherit (underline italic)))))
 '(match ((t (:foreground "#aea7c3" :background "#3c3e55"))))
 '(next-error ((t (:background "#573f5d"))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'luke)
