(deftheme luke
  "Created 2025-11-27.")

(custom-theme-set-faces
 'luke
 '(default ((t ( :slant normal :underline nil :overline nil :extend nil :strike-through nil :box nil :inverse-video nil :foreground "#D8DEE9" :background "#212121" :stipple nil :inherit nil))))
 '(window-divider ((t (:foreground "#444444"))))
 '(vertical-border ((t (:foreground "#444444"))))
 '(cursor ((t (:background "#D8DEE9"))))
 '(escape-glyph ((t (:foreground "#D08770"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:weight bold :foreground "#88C0D0"))))
 '(highlight ((t (:foreground "#88C0D0" :background "#434C5E"))))
 '(region ((t (:extend t :background "#434C5E"))))
 '(shadow ((t (:foreground "#4C566A"))))
 '(secondary-selection ((t (:extend t :background "#434C5E"))))
 '(trailing-whitespace ((t (:foreground "#4C566A"))))
 '(font-lock-bracket-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-builtin-face ((t (:foreground "#81A1C1"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#616e88"))))
 '(font-lock-comment-face ((t (:foreground "#616e88"))))
 '(font-lock-constant-face ((t (:foreground "#81A1C1"))))
 '(font-lock-delimiter-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-doc-face ((t (:foreground "#616e88"))))
 '(font-lock-doc-markup-face ((t (:inherit (font-lock-constant-face)))))
 '(font-lock-escape-face ((t (:inherit (font-lock-regexp-grouping-backslash)))))
 '(font-lock-function-call-face ((t (:inherit (font-lock-function-name-face)))))
 '(font-lock-function-name-face ((t (:foreground "#88C0D0"))))
 '(font-lock-keyword-face ((t (:foreground "#81A1C1"))))
 '(font-lock-negation-char-face ((t (:foreground "#81A1C1"))))
 '(font-lock-number-face ((t nil)))
 '(font-lock-misc-punctuation-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-operator-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:weight bold :foreground "#5E81AC"))))
 '(font-lock-property-name-face ((t (:inherit (font-lock-variable-name-face)))))
 '(font-lock-property-use-face ((t (:inherit (font-lock-property-name-face)))))
 '(font-lock-punctuation-face ((t nil)))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#EBCB8B"))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#EBCB8B"))))
 '(font-lock-string-face ((t (:foreground "#A3BE8C"))))
 '(font-lock-type-face ((t (:foreground "#8FBCBB"))))
 '(font-lock-variable-name-face ((t (:foreground "#D8DEE9"))))
 '(font-lock-variable-use-face ((t (:inherit (font-lock-variable-name-face)))))
 '(font-lock-warning-face ((t (:foreground "#EBCB8B"))))
 '(button ((t (:box (:line-width (2 . 2) :color "#D8DEE9" :style pressed-button) :foreground "#88C0D0" :background "#2E3440"))))
 '(link ((t (:underline (:color foreground-color :style line :position nil)))))
 '(link-visited ((t (:underline (:color foreground-color :style line :position nil)))))
 '(fringe ((t (:foreground "#D8DEE9" :background "#212121"))))
 '(header-line ((t (:foreground "#D8DEE9" :background "#434C5E"))))
 '(tooltip ((t (:foreground "#2E3440" :background "#D8DEE9"))))
 '(mode-line ((t (:foreground "#88C0D0" :background "#4C566A"))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:foreground "#D8DEE9" :background "#3B4252"))))
 '(isearch ((t (:foreground "#2E3440" :background "#88C0D0"))))
 '(isearch-fail ((t (:foreground "#BF616A"))))
 '(lazy-highlight ((((class color) (min-colors 88) (background light)) (:distant-foreground "black" :background "paleturquoise")) (((class color) (min-colors 88) (background dark)) (:distant-foreground "white" :background "paleturquoise4")) (((class color) (min-colors 16)) (:distant-foreground "white" :background "turquoise3")) (((class color) (min-colors 8)) (:distant-foreground "white" :background "turquoise3")) (t (:underline (:color foreground-color :style line :position nil)))))
 '(match ((t (:inherit (isearch)))))
 '(next-error ((t (:inherit (error)))))
 '(query-replace ((t (:foreground "#88C0D0" :background "#434C5E")))))

(provide-theme 'luke)
